### ISSUE TITLE
improve performance of stack search on projects page

### ISSUE THREAD

**Issue by susanev** [pulumi/service-requests#103]
the stack search is unusable in projects with a large number of stacks

here is a recent quote from a user
>We have a lot of stacks in our company and the search functionality is almost unusable and incredibly slow. Taking +2 minutes at times each time I even type a letter. Any improvement in the listing of searching of stacks where a company has a large number would be a huge improvement.

**Comment by EvanBoyle** [comment]
closing as duplicate of https://github.com/pulumi/service-requests/issues/56
