### ISSUE TITLE
Add a New project button to the dashboard

### ISSUE THREAD

**Issue by cnunciato** [pulumi/service-requests#124]
I often find myself looking for a New Project button on this page:

![image](https://user-images.githubusercontent.com/274700/199592742-3bc107a7-7a35-4847-8f4d-02b8f4d8343a.png)

It'd be great if there were one! Makes sense it's on the Stacks page also, but something about the layout we have now feels like it should be on the Dashboard, too.

**Comment by susanev** [comment]
lol, guess what @cnunciato 
@anita-trimbur and @sean1588 are already on this.
https://github.com/pulumi/pulumi-service/pull/11000

**Comment by cnunciato** [comment]
Woo! Closing because that's awesome.
