### ISSUE TITLE
Support for OpenID Connect to obtain temporary credentials for Pulumi Deployments

### ISSUE THREAD

**Issue by eriklz** [pulumi/service-requests#144]
Infrastructure deployment to a cloud provider often need extensive credentials to support many use cases. It is preferable to avoid setting permanent credentials for any access outside of the cloud provider.
This would be a useful feature to have if Pulumi Deployments in the Pulumi Service is used.
There are multiple ways to solve this problem.

One approach is to use OpenID Connect, where a trust relationship is set up between the cloud provider and Pulumi Service, in this case. For each deployment, OIDC allows the Pulumi service to get properly scoped temporary credentials for a particular deployment, if set up properly. No deployment credentials would need to be stored permanently.

## Affected feature

Pulumi Deployments is the affected service feature.

This is a different approach to solve the same problem as in #141 
The advantage with OIDC is that it should be a one-time setup for the trust relationship between the Pulumi service side and the cloud provider side, pretty much. No logic needed to generate and push credentials for each deployment setup in the Pulumi service, or at least simpler logic from a user perspective.

GitHub Actions and Bitbucket Pipelines have OIDC support if one chooses to use their workflow instead of what is in Pulumi service.

**Comment by EvanBoyle** [comment]
Thanks for opening @eriklz. We're investigating what it would take to get this set up.

**Comment by EvanBoyle** [comment]
Leaving this open pending docs

**Comment by EvanBoyle** [comment]
OIDC support for AWS, Azure, and GCP is now available for Pulumi Deployments!

See the user guide here: https://www.pulumi.com/docs/guides/oidc/ as well as examples in the REST API documentation: https://www.pulumi.com/docs/reference/deployments-rest-api/#operationcontext

OIDC can be configured within the console for push to deploy, and can be used directly with the REST API. Looking forward to feedback!
