### ISSUE TITLE
Pulumi web UI shows all items as complete, but task hasn't finished - some items aren't being shown

### ISSUE THREAD

**Issue by mikemaccana** [pulumi/service-requests#2]
The Pulumi web UI marks all jobs as complete, with none outstanding, but the deploy hasn't finished:

![image](https://user-images.githubusercontent.com/172594/122473664-14841800-cfba-11eb-9f7e-a1486141e8f1.png)

The command line UI however shows there are outstanding tasks - eg the autoscale group:

![image](https://user-images.githubusercontent.com/172594/122473760-32517d00-cfba-11eb-91dc-e56e3ad617d0.png)

It seems the web UI is missing items (eg the autoscale group) that are shown in the command line UI.

**Comment by komalali** [comment]
I believe this was closed out as part of https://github.com/pulumi/pulumi-service/commit/2619e137f6935cddf9d91ea33dc266d23f472ac5 - feel free to reopen if that isn't the case.
