### ISSUE TITLE
Is Anyone Checking Joe Duffy's Inbox?

### ISSUE THREAD

**Issue by zscott** [pulumi/service-requests#204]
Product: 5 stars - love it -  ~100 resources deployed in first few days

Customer Communication seems completely broken. 

**Monday, Mar 13**
Received an email from Joe Duffy (obviously a marketing campaign). The email invited me to provide feedback and all I had to do was "Please just reply to this email and I'll be sure to get back to you". 

**Monday, Mar 13**
I replied with an email that opens like this:
"First, I have to say Pulumi is an amazing service. I feel like it lets us program the internet. I kicked the tires on Terraform first and you guys outclass Terraform. Nicely done!"

I went on to describe our use-case and ask for guidance.

**Sunday, Mar 19th** (6 days later)
I sent another email because I still didn't see a reply.
That one opens like this:
"Hi again Joe,

Assuming my first message below didn’t make it to your inbox. Will try again.

In addition to the below, wondering if your team has plans to be at AWS re:invent 2023?"

**Today is Wed Mar 22** (9 days after my first response)

So 2 things:
1) Either your campaign is broken or Joe Duffy needs more help.
2) I would still like to talk to someone. The product seems great, but I'm a bit nervous about what support might look like should I decide to pay. I was 100% sold, but now I'm honestly on the fence.

## General Feedback

<img width="519" alt="Screenshot 2023-03-22 at 1 25 53 PM" src="https://user-images.githubusercontent.com/622556/227015727-04c4baa3-ceab-4379-81ff-4256d7a1e019.png">
<img width="517" alt="Screenshot 2023-03-22 at 1 28 22 PM" src="https://user-images.githubusercontent.com/622556/227015783-6bb44e01-ff05-4f8e-90f3-02ea12230b2e.png">

**Comment by ericrudder** [comment]
Sent mail to zach.mobile@gmail.com to get some time for discussion.
