### ISSUE TITLE
Where to report product failures and request support?

### ISSUE THREAD

**Issue by proyVolt** [pulumi/service-requests#205]
I don't see anywhere on the dashboard to report bugs or initiate some sort of support action. I just had a glitch strand ~60 cloud resources and I don't know what I need to do to make sure y'all know about this so it doesn't happen again.
## General Feedback
Links usually work pretty well for stuff like this. I searched on the dashboard for 'support', 'isssue', 'bug', etc... but didn't see anything.

**Comment by lukehoban** [comment]
> I don't see anywhere on the dashboard to report bugs or initiate some sort of support action. 

You are in the right place!  You just reported a bug :-).

> I just had a glitch strand ~60 cloud resources and I don't know what I need to do to make sure y'all know about this so it doesn't happen again.

Could you provide details of the issue?  What exactly do you mean by "strand" and "glitch" here?

You can provide details in two ways:
1. Open an issue here in https://github.com/pulumi/service-requests/issues if you believe it's a general thing
2. Open a ticket with support at https://www.pulumi.com/support/ (also linked from your orgs Settings panel in the SaaS)

I'll close this out for now - but look forward to hearing from you at either of the above.
