### ISSUE TITLE
Provide Transfer Project Button

### ISSUE THREAD

**Issue by MitchellGerdisch** [pulumi/service-requests#23]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Currently to move a project from one org to another requires moving each stack in the project.
It would be useful to have a button that allows one to move all the stacks at once.

### Affected area/feature

Console Settings - Transfer Stack button.

**Comment by susanev** [comment]
this is done
