### ISSUE TITLE
Update subscription section to make how to upgrade clearer

### ISSUE THREAD

**Issue by nimbinatus** [pulumi/service-requests#25]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

In attempting to upgrade an account to a paid account, it took me a little while to realize that you need to create a different org before you can upgrade. It was not clear that my personal org, since it will be forever free, cannot be upgraded (I didn't realize my personal workspace wasn't considered an org in our layout, basically). I can easily see a user in a hurry thinking there's no way to upgrade or not realizing they could.

As an interim solution, putting a note in this spot under **Billing and Usage** in the **Settings** tab that personal orgs are always free and upgrading is done by creating a new organization would be helpful:

![Screen Shot 2021-11-01 at 2 46 26 PM](https://user-images.githubusercontent.com/1538692/139732673-739042fb-1764-484d-a18b-130ecf6bcb6d.png)

Beyond that, perhaps adding a "Create an Org and Upgrade" button or something like that might help? A one-action build of what they're actually looking to do? And perhaps directions on how to migrate important configs and stacks would be useful;  at one point, I probably had a bunch of stuff I spun up on my own personal spaces on another platform. It was easier to give people access rather than moving everything and figuring out what configs broke.

### Affected area/feature

Pulumi Service

**Comment by susanev** [comment]
this has been addressed with the new user experience
