### ISSUE TITLE
adjust repo name from console-requests to service-requests

### ISSUE THREAD

**Issue by susanev** [pulumi/service-requests#36]
recently we removed the name Pulumi Console from our docs, marketing website, and the service UI. we are now using Pulumi Service as the only official name. we can still use `console` to refer to the UI of the service, but should not be using Pulumi Console. as such, we may want to consider adjusting the name of this repo to align with this name change.

related issues:
https://github.com/pulumi/pulumi-hugo/issues/934
https://github.com/pulumi/pulumi-service/issues/7886

relatedly we may want to also rename the community slack channel, unsure of where to submit that request.

**Comment by EvanBoyle** [comment]
Done. I don't have permissions on community slack but I requested that it get updated. Closing this issue out.
