### ISSUE TITLE
Duplicated entries in org list when switching to SAML SSO

### ISSUE THREAD

**Issue by pawelros** [pulumi/service-requests#50]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

### Steps to reproduce

1. Have an org using GitHub SSO
2. Switch your org to SAML SSO (i.e. Okta)
3. Login as an existing user using GitHub
4. Go to user settings -> Identities -> Connect SAML SSO and link your user to SAML SSO (i.e. in Okta)
5. (optional) Log out and Log in using SSO provider.

Expected: 
I should see my pulumi org only once on a list
Actual: 
I can see two or more orgs with the same name (while doing some SSO testing, adding and removing users from the org I managed to see my org 3x on a list). Here an example with 2x:
![image](https://user-images.githubusercontent.com/645656/158852265-983552fb-ddc1-4b24-9d1f-7a27f3366e70.png)

I believe the list is builded in a browser and when user changes SSO identity something changes that makes org to be multiplied.
All multiplied orgs redirect to the same org so it is not a big deal, though users are getting confused.

**Comment by kimberleyamackenzie** [comment]
Hi @pawelros - thanks for surfacing this! Do these duplicate orgs remain in your org chooser indefinitely, or do they eventually disappear?  If they do disappear, is it after page refreshes/opening new tabs, or after some specific action you take?

**Comment by pawelros** [comment]
Hey @kimberleyamackenzie, unfortunately I cannot reproduce it anymore as I finished my SSO tests and deleted my test SSO org. Duplicated entries were persistent between page refreshes and new tabs.

**Comment by kimberleyamackenzie** [comment]
Thanks for the report and info!  We'll investigate more on our end, and keep this ticket updated.

**Comment by EvanBoyle** [comment]
This has been fixed!
