### ISSUE TITLE
PR bot should remove old comments

### ISSUE THREAD

**Issue by nesl247** [pulumi/service-requests#59]
As discussed [here](https://pulumi-community.slack.com/archives/C84L4E3N1/p1588085596200800), the bot should automatically remove old comments.

Something that happens quite frequently for us is to have a PR change 20+ projects. Each project has 2-3 stacks (one per environment). 

If a PR is opened, that means we have a minimum of 40 comments from the pulumi bot. Now imagine that you push due to code reviews, 5 more commits. Now you have 200 comments from the pulumi bot. This makes it nearly impossible to review the PR because finding real comments becomes easy.

I suggest removing old comments at minimum, as they no longer mean anything anyways. Another option would be to make a single comment by pulumi, that contains all updates for that PR, rather than a comment per stack.

**Comment by henworth** [comment]
If we could surface this backlog item it would be most appreciated. I'd also welcome the ability to use normal PR comments rather than review comments. That would at least open up the ability to allow folks to delete stale comments manually.

**Comment by blampe** [comment]
This will be rolling out over the next couple hours. Please let me know if you see any problems or unexpected comment minimization! 

Note that comments will be minimized, not deleted. This way there is still historical context if you need it for debugging.

Note also that if you have a PR that was opened before https://github.com/pulumi/service-requests/issues/74 was resolved, its "review comments" will still be shown. GitHub doesn't allow these to be minimized.

**Comment by expelledboy** [comment]
I have noticed the difference already, thank you :)

**Comment by krisdock** [comment]
can the original request be revisited? the request for using normal comments was addressed, but the original ask here was to have the pulumi app remove previous comments on subsequent runs. is that planned?
