### ISSUE TITLE
Stacks are not being found

### ISSUE THREAD

**Issue by alexbowers** [pulumi/service-requests#65]
### What happened?

```
pulumi preview --cwd environments --stack jobilla/production --color always --verbose 9 --logtostderr --logflow

The stack 'jobilla/production' does not exist.

If you would like to create this stack now, please press <ENTER>, otherwise press ^C: ^C
```

### Steps to reproduce

Run `pulumi preview --cwd environments --stack jobilla/production --color always --verbose 9 --logtostderr --logflow`

### Expected Behavior

I expected my stacks to work, and for the preview to work.

### Actual Behavior

I got the error shown above. I did not proceed because I don't want to lose my stack or anything.

### Versions used

CLI
Version      3.33.1
Go Version   go1.18.2
Go Compiler  gc

Plugins
NAME        VERSION
aws         4.35.0
aws-native  0.8.0
docker      3.0.0
eks         0.31.0
kubernetes  3.10.0
mysql       3.1.0
nodejs      unknown

Host
OS       darwin
Version  12.3.1
Arch     x86_64

This project is written in nodejs (/Users/alexbowers/.nvm/versions/node/v16.13.1/bin/node v16.13.1)

Backend
Name           pulumi.com
URL            https://app.pulumi.com/alexbowers
User           alexbowers
Organizations  alexbowers

NAME                 VERSION
@pulumi/eks          0.31.0
@pulumi/kubernetes   3.10.0
@pulumi/kubernetesx  0.1.6
@pulumi/pulumi       3.4.0
@types/netmask       1.0.30
@types/node          10.17.60
@pulumi/awsx         0.30.0
netmask              2.0.2
@pulumi/aws          4.35.0
yaml                 1.10.2
@pulumi/aws-native   0.8.0

Pulumi locates its logs in /var/folders/c9/8j6tg8193dv5b30b1kbytl7c0000gn/T/ by default
warning: Failed to get information about the current stack: No current stack

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by aureq** [comment]
Hi @alexbowers thanks for reporting this issue. Do you happen to have your user linked to your Gitlab identity ? If so, could you please have a look at https://status.pulumi.com/incidents/tpdwlgb9x4qy

Thank you

**Comment by alexbowers** [comment]
That resolved it. Thanks
