### ISSUE TITLE
GitHub app should post comments to PRs that were opened before the app was installed+configured

### ISSUE THREAD

**Issue by aviflat** [pulumi/service-requests#71]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Last week I had a PR open in which I started using the GitHub Actions (GHA), uh, Action, to run Pulumi in response to certain events. I wasn’t thrilled with the comment-posting feature of the Action, so I decided to try the GitHub “app” instead. I got it installed and configured, and then eventually triggered the GHA workflow+job to run the Pulumi Action. I was then perplexed that the “app” didn’t post comments to the PR as I’d expected. I could tell that the app was “running” because it _was_ posting “checks” to the PR. But for some reason it wasn’t posting comments.

Later, after I’d merged that initial PR, I opened a follow-up PR which also ran the Pulumi Action in a job. And then at that point, on that PR, the app _did_ post comments with the preview diffs.

I inferred from all that, that the app for some (probably technical) reason doesn’t post comments to PRs that were already open when it was installed.

That’s not _necessarily_ a big deal, but it wasn’t what I expected, and at first I didn’t understand what was happening, and as far as I could tell, the app just wasn’t working. I didn’t at first have any idea why. So I ended up spending a few hours at least, submitting a support request, starting [a chat thread](https://pulumi-community.slack.com/archives/C84L4E3N1/p1653406926763059?thread_ts=1653406774.288119&cid=C84L4E3N1), and crafting a follow-up GHA job to post a warning to the PR that reviewers need to navigate to the “checks” and review the diffs.

So: I suggest that either the app be updated so that it _will_ post comments to PRs that were already opened when it was installed, _or_ the docs be updated with a note that the app won’t be fully functional for PRs that predate the installation.

### Affected area/feature

The GitHub “app”

**Comment by AaronFriel** [comment]
If the service team sees something I didn't, we can close pulumi/actions#621 and perhaps follow up here:
- https://github.com/github/feedback/discussions/17344

**Comment by blampe** [comment]
I think I also ran into this while doing some testing, and I agree it's surprising behavior.

@AaronFriel I think I agree if I'm reading https://github.com/pulumi/actions/issues/621 correctly. If the idea is to post a comment for the first time on a closed PR I think that's very doable.

**Comment by blampe** [comment]
@aviflat this fix is also live. Let us know if you see any more issues.

**Comment by aviflat** [comment]
will do — thanks!
