### ISSUE TITLE
Allow the GitHub app to post PR comments rather than PR reviews

### ISSUE THREAD

**Issue by henworth** [pulumi/service-requests#74]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

We recently started using the app and one thing that has come up the most so far is how PR comments are implemented. I know there has been a lot of discussion regarding the ability to remove stale comments, but what I’d like to get some insight on is why they are implemented as review comments and not just normal PR comments. I would also welcome a configurable option to control the type of comment (review or regular), as this would at least give the ability to delete comments.

I initially brought this up [here](https://pulumi-community.slack.com/archives/C02DM3GH4TY/p1656088905297039) in the community slack.

### Affected area/feature

GitHub App

**Comment by blampe** [comment]
This is an extremely reasonable request. I don't think there's a strong reason for these to be review comments.

**Comment by blampe** [comment]
@henworth this change is now live, thanks for the great suggestion. Keep them coming :)

> I know there has been a lot of discussion regarding the ability to remove stale comments

Stay tuned - I'm planning some additional work to hide these automatically. My hope is this ability tp manually hide/delete unwanted comments can act as stopgap until that's ready.
