### ISSUE TITLE
Billing Admin Role in the Pulumi Service

### ISSUE THREAD

**Issue by lukehoban** [pulumi/service-requests#76]
A Billing Manager role will give users permissions to access and edit only billing information, with no read or write permissions for stacks. This role is for when you need someone in your Organization to manage billing operations but you do not want them to have any permissions beyond that. Billing Managers will only be able to be invited or added to the Organization by Organization Admins. Once added, the only information a Billing Manager will see is metrics about the Organization and the Billing and Usage page.

**Comment by meagancojocar** [comment]
Closing out as we have released this now! Please see the [blog post](https://www.pulumi.com/blog/billing-managers) and [documentation](https://www.pulumi.com/docs/intro/pulumi-service/billing-managers) for more details.
