### ISSUE TITLE
Make the web ui display "pending" operations

### ISSUE THREAD

**Issue by antifuchs** [pulumi/service-requests#82]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

It's my understanding that the information flow between the pulumi cli and the hosted pulumi service is approximately as follows:

1. pulumi client/provider will mention the intent to kick off an action to the backing store (the pulumi hosted service)
2. that sets a "pending" operation on the state
3. the provider polls the service that it interfaces with to see if the resource is created
4. when the pulumi client/provider is done creating the resource, it marks the pulumi resource as finished.

So that means the UI could display "pending" resources, and I think it should! That would 100% fix all the issues I'm having with long-running updates that seem "stuck" with no ability to see what they are stuck on.

### Affected area/feature

The Pulumi service.

**Comment by EvanBoyle** [comment]
@antifuchs thanks for opening this issue. It sounds like the core problem here is that the update logs displayed in app.pulumi.com don't make it clear that there are resources that have started updating but haven't finished. 

I took a look at one of our stacks that was in the process of updating. There was a docker resource that was in the process of building and updating, but it didn't appear in the resource list. All resources showed that there operations were complete:

![image](https://user-images.githubusercontent.com/2553171/185677371-23e0027f-6e6e-4e83-b5fd-293ff6e6b207.png)

**Comment by antifuchs** [comment]
Yep, that's exactly my experience, too! Thanks for adding the screenshot & confirming.
