### ISSUE TITLE
Copy buttons on the Stack Settings page

### ISSUE THREAD

**Issue by cnunciato** [pulumi/service-requests#91]
I've found myself returning to this page more frequently lately (iterating on multiple stacks in a project), and I've been manually copy-pasting the snippets. Realized it'd be a teeny bit nicer if there were copy buttons here like we have elsewhere:

![image](https://user-images.githubusercontent.com/274700/186468530-0a9a0ddf-32d4-4218-a0b0-23e90026ef06.png)

**Comment by susanev** [comment]
i was just chatting about this page with Jonelle, def makes sense to add copy buttons here. will slot it for next iteration.
