### ISSUE TITLE
Updates by org tokens don't display the name of the token that was used

### ISSUE THREAD

**Issue by EvanBoyle** [pulumi/service-requests#95]
Only the name of the org is shown in the update history. We should also show the token name. Even just showing it on hover would be an improvement. 

![image](https://user-images.githubusercontent.com/2553171/187801187-8acaf19a-dbc7-4c3a-9dea-af30521592ea.png)

**Comment by djgrove** [comment]
This has been fixed in the latest merge. Will close this once we have deployed the payload that will fix this.

**Comment by djgrove** [comment]
Closing as prod deploy is going out
